name: Generate Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

            - name: Create Cordova Project
        run: |
          cordova create myApp com.charles.music "Music"
          rm -rf myApp/www/*
          # Copy your main files
          cp index.html myApp/www/
          cp style.css myApp/www/
          cp script.js myApp/www/
          # If you have an images folder, copy it too
          # cp -r images/ myApp/www/


      - name: Setup Android Platform
        run: |
          cd myApp
          cordova platform add android

      - name: Compile APK
        run: |
          cd myApp
          cordova build android --debug

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Music-APK
          path: myApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
